{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: frontend
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: "{{ .Values.frontend.resources.cpu }}"
              memory: "{{ .Values.frontend.resources.memory }}"
            limits:
              cpu: "{{ .Values.frontend.resources.cpu }}"
              memory: "{{ .Values.frontend.resources.memory }}"
          # Add volume mounts for configuration files
          volumeMounts:
            - name: frontend-config-volume
              mountPath: /path/to/config
              readOnly: true
      # Define volumes to mount ConfigMap
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-config
            # Add other ConfigMap options here if needed
{{- end -}}
