mysql:
  enable: true
  password: "Ab123456"
  qkd_dump_file: "config/dump.sql"
  image: mysql:8.0.26
  service:
    type: NodePort ## 不需要暴露时，需要将该配置置空
    nodePort: 32667
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi
  