


modules:
  - frontend:
      enabled: true
      image:
        repository: your-repo/frontend-app
        tag: v1.0.0
        pullPolicy: IfNotPresent
      resources:
        cpu: "300m"
        memory: "512Mi"
      service:
        type: ClusterIP
        port: 80
  