{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  labels:
    app: {{ .Release.Name }}
    component: frontend
data:
  # 您的配置文件内容可以在这里定义
  config.yaml: |
    key1: value1
    key2: value2
{{- end -}}